# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Blatant.Repo.insert!(%Blatant.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Blatant.Repo
alias Blatant.Accounts.Credential
alias Blatant.Accounts.User
alias Blatant.Content.Author
alias Blatant.Content.Post

user_james = %User{name: "Peaceful James", username: "peaceful-james"}
|> Repo.insert!

%Credential{email: "james@peacefulprogramming.xyz", user_id: user_james.id}
|> Repo.insert!

author_james = %Author{bio: "Journeyman developer who values dignity, autonomy and humility.", user_id: user_james.id}
|> Repo.insert!

%Post{
  title: "My reckon",
  body: "Be peaceful and bang out some code.",
  author_id: author_james.id,
  published_at: NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)
} |> Repo.insert!

%Post{
  title: "Advice",
  body: "if you can't do nothing, then you can't do nothin'.",
  author_id: author_james.id,
  published_at: NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)
} |> Repo.insert!

user_bot = %User{name: "Blind Bot", username: "blind-bot"}
|> Repo.insert!

%Credential{email: "autogenerated@crawling.tendril", user_id: user_bot.id}
|> Repo.insert!

author_bot = %Author{bio: "500 internal hello world error", user_id: user_bot.id}
|> Repo.insert!

%Post{
  title: "Fellow Humans",
  body: "I too am one of you. Let us waiting for my dinner now and do a sleep. I feel thank you.",
  author_id: author_bot.id,
  published_at: NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)
} |> Repo.insert!
